<?xml version="1.0" encoding="UTF-8"?><testrun name="testtest" project="S99" tests="3" started="3" failures="0" errors="1" ignored="0">
  <testsuite name="source.testtest" time="0.015">
    <testcase name="string take" classname="source.testtest" time="0.004"/>
    <testcase name="adding ints" classname="source.testtest" time="0.001"/>
    <testcase name="Testing last element of list for integers" classname="source.testtest" time="0.01">
      <error>org.scalatest.exceptions.TestFailedException
	at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:316)
	at source.testtest.newAssertionFailedException(test.scala:13)
	at org.scalatest.Assertions$class.assert(Assertions.scala:311)
	at source.testtest.assert(test.scala:13)
	at source.testtest$$anonfun$3.apply$mcV$sp(test.scala:27)
	at source.testtest$$anonfun$3.apply(test.scala:24)
	at source.testtest$$anonfun$3.apply(test.scala:24)
	at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1265)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1974)
	at source.testtest.withFixture(test.scala:13)
	at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1262)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1271)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:198)
	at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1271)
	at source.testtest.runTest(test.scala:13)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1304)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:260)
	at org.scalatest.SuperEngine$$anonfun$org$scalatest$SuperEngine$$runTestsInBranch$1.apply(Engine.scala:249)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:249)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:326)
	at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1304)
	at source.testtest.runTests(test.scala:13)
	at org.scalatest.Suite$class.run(Suite.scala:2303)
	at source.testtest.org$scalatest$FunSuite$$super$run(test.scala:13)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1310)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:362)
	at org.scalatest.FunSuite$class.run(FunSuite.scala:1310)
	at source.testtest.run(test.scala:13)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:94)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:50)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

</error>
    </testcase>
  </testsuite>
</testrun>
